# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import userdefinedfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metadata', userdefinedfields.fields.ExtraFieldsJSONField(blank=True, default=dict)),
            ],
        ),
    ]
