# Generated by Django 2.0.3 on 2018-06-14 11:03

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('siteconfig', '0006_auto_20180614_2054'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='DisplayCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=32)),
                ('values', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=32, verbose_name='Field group')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=50, verbose_name='Display name')),
                ('name', models.SlugField()),
                ('field_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('widget', models.CharField(choices=[('text', 'Text'), ('multiline-text', 'Multiline Text'), ('integer', 'Number'), ('choice', 'Choice'), ('date', 'Date')], default='text', max_length=32)),
                ('default', models.CharField(blank=True, default='', max_length=1024)),
                ('in_list', models.BooleanField(default=True, verbose_name='Show in list view?')),
                ('required', models.BooleanField(default=False, verbose_name='Should field be required?')),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('content_type', 'group', 'order'),
            },
        ),
        migrations.AddField(
            model_name='displaycondition',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdefinedfields.ExtraField'),
        ),
        migrations.AlterUniqueTogether(
            name='extrafield',
            unique_together={('content_type', 'name')},
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
