# Generated by Django 2.0.6 on 2018-07-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='widget',
            field=models.CharField(choices=[('text', 'Text'), ('multiline-text', 'Multiline Text'), ('integer', 'Integer'), ('choice', 'Choice'), ('date', 'Date')], default='text', max_length=32),
        ),
    ]
