# Generated by Django 3.2.12 on 2022-05-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdefinedfields", "0003_auto_20201120_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="widget",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("multiline-text", "Multiline Text"),
                    ("integer", "Integer"),
                    ("choice", "Choice"),
                    ("date", "Date"),
                    ("decimal", "Decimal"),
                ],
                default="text",
                max_length=32,
            ),
        ),
    ]
